VERSION: 5
env: {}
jobs:
  airsonic-advanced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .#airsonic-advanced
name: airsonic-advanced
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
