VERSION: 5
env: {}
jobs:
  live-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .#nixosConfigurations.live-iso.config.system.build.toplevel
          --dry-run
name: live-iso
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
